name: release to rubygems

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Build gem
        uses: scarhand/actions-ruby@master
        with:
          args: build *.gemspec
      - name: Publish gem
        uses: scarhand/actions-ruby@master
        env:
          RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_JENKINS_GH_ACTIONS_PUSH }}
        with:
          args: push *.gem
