name: RSpec tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  rspec_tests:
    name: Puppet ${{ matrix.cfg.puppet_version }}, Ruby ${{ matrix.cfg.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - {puppet_version: '7', ruby: '2.7'}
          - {puppet_version: '7', ruby: 'jruby-9.3.7.0'}
          - {puppet_version: '8', ruby: '3.2'}
          - {puppet_version: '8', ruby: 'jruby-9.4.2.0'}
    env:
      PUPPET_GEM_VERSION: ~> ${{ matrix.cfg.puppet_version }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Ruby version ${{ matrix.cfg.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.cfg.ruby }}
      - name: Update rubygems and install gems
        run: |
          bundle config set without development
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake
